server:
  port: 8888
---
spring:
  application:
    name: configserver
---
spring:
  cloud:
    config:
      enabled: false
      server: 
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
#          uri: file://D:/IBM/Workspace/SpringCloud/Microservices-Demo/ConfigData/Microservices-With-Spring-Student-Files
#          searchPaths: ConfigData
           
