###############################################################
### Default configuration for development environment.      ###
###############################################################
version: '2'
services:
  eureka:
    restart: always
    build: ./micro1-eureka-server
    command: -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    network_mode: "host"
    ports:
      - "8761:8761"
  config:
    restart: always
    build: ./micro2-config-server
    command: -Djava.security.egd=file:/dev/./urandom -DPORT=8888 -jar /app.jar
    network_mode: "host"
    ports:
      - "8888:8888"
    depends_on:
      - "eureka"
  purchase:
    restart: always
    build: ./micro3-word-server
    command: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=purchase -DPORT=8081 -jar /app.jar
    network_mode: "host"
    ports:
      - "8081:8081"
    depends_on:
      - "eureka"
      - "config"
  customer:
    restart: always
    build: ./micro3-word-server
    command: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=customer -DPORT=8082 -jar /app.jar
    network_mode: "host"
    ports:
      - "8082:8082"
    depends_on:
      - "eureka"
      - "config"
  offer:
    restart: always
    build: ./micro3-word-server
    command: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=offer -DPORT=8083 -jar /app.jar
    network_mode: "host"
    ports:
      - "8083:8083"
    depends_on:
      - "eureka"
      - "config"
  payment:
    restart: always
    build: ./micro3-word-server
    command: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=payment -DPORT=8084 -jar /app.jar
    network_mode: "host"
    ports:
      - "8084:8084"
    depends_on:
      - "eureka"
      - "config"
  product:
    restart: always
    build: ./micro3-word-server
    command: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=product -DPORT=8085 -jar /app.jar
    network_mode: "host"
    ports:
      - "8085:8085"
    depends_on:
      - "eureka"
      - "config"
  order:
    restart: always
    build: ./micro4-order-server
    command: -Djava.security.egd=file:/dev/./urandom -jar -DSERVER_PORT=8020 /app.jar
    network_mode: "host"
    ports:
      - "8020:8020"
    depends_on:
      - "eureka"
      - "config"
      - "purchase"
      - "customer"
      - "offer"
      - "payment"
      - "product"