---
# Properties active for ALL profiles:
server:
  port: ${SERVER_PORT:8761}
eureka:
  instance:
    preferIpAddress: ${PREFER_IP_ADDRESS:false}
  client: 
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://${SERVER_IP:localhost}:${SERVER_PORT:8761}/eureka/

spring.cloud.config.discovery.enabled: true
      